---
# tasks file for named_apply_conf_and_zone
- name: Find DNS hostnames
  ansible.builtin.find:
    paths: "{{ work_dir }}"
    recurse: yes
    file_type: directory
    patterns: "*.*.domain.local"
    excludes: "{{ excludes }}"
  register: dns_hosts

- name: Extract DNS hostnames
  set_fact:
    hostnames_list: "{{ hostnames_list | default([]) + [item.path.split('/')[-1]] }}"
    path_to_dir: "{{ path_to_dir | default([]) + [item.path] }}"
  with_items: "{{ dns_hosts.files }}"

- name: Check DNS config and DNS zone files
  ansible.builtin.include_tasks: check_dns_files.yml
  vars:
    dns_hostname: "{{ hostnamed_dirname_form_list.0 }}"
    path_to_hostname_dir: "{{ hostnamed_dirname_form_list.1 }}"
  loop: "{{ hostnames_list | zip(path_to_dir) }}"
  loop_control:
    loop_var: hostnamed_dirname_form_list

- name: Apply config files
  ansible.builtin.include_tasks: apply_conf.yml
  vars:
    dns_hostname: "{{ hostnamed_dirname_form_list.0 }}"
    path_to_hostname_dir: "{{ hostnamed_dirname_form_list.1 }}"
  loop: "{{ hostnames_list | zip(path_to_dir) }}"
  loop_control:
    loop_var: hostnamed_dirname_form_list